# Build Stage
FROM rust:1.80 as builder
WORKDIR /app
COPY . .
RUN cargo build --release -p yolofi_browser

# Runtime Stage
FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/yolofi_browser /usr/local/bin/
CMD ["yolofi_browser"]
